---
- hosts: all
  gather_facts: False
  become: true
  vars_files:
    - "vars/vaulted.yml"
  vars:
    root_domain: ung.prosa.dk
    services:
      - nginx-proxy
      - default
      - rocket-chat
      - watchtower
  tasks:
    - import_role:
        name: base
    - import_role:
        name: docker