---
- name: ensure itpol_valg network exists
  docker_network:
    name: itpol_valg

- name: ensure database schema exists
  copy:
    src: itpol_valg-create.sql
    dest: "{{ itpol_valg.volume_folder }}/db-init/"

- name: ensure itpol_valg-db exists
  docker_container:
    name: itpol_valg-db
    image: mariadb
    restart_policy: unless-stopped
    networks:
      - name: itpol_valg
    env:
      MYSQL_ROOT_PASSWORD: "{{ itpol_valg_secrets.db_root_pass }}"
      MYSQL_DATABASE: valg
      MYSQL_USER: "{{ itpol_valg_secrets.db_user }}"
      MYSQL_PASSWORD: "{{ itpol_valg_secrets.db_pass }}"
    volumes:
      - "{{ itpol_valg.volume_folder }}/db-data:/var/lib/mysql"
      - "{{ itpol_valg.volume_folder }}/db-init/:/docker-entrypoint-initdb.d"

- name: ensure itpol_valg exists
  docker_container:
    name: itpol_valg
    image: prosaung/valg.prosa.dk-default
    restart_policy: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    networks:
      - name: itpol_valg
      - name: external_services
    links:
      - "itpol_valg-db:db"
    env:
      VIRTUAL_HOST: "{{ itpol_valg.domain }}"
      VIRTUAL_PORT: "80"
      LETSENCRYPT_HOST: "{{ itpol_valg.domain }}"
      LETSENCRYPT_EMAIL: "{{ letsencrypt_email }}"
      DB_HOST: db
      DB_NAME: valg
      DB_USER: "{{ itpol_valg_secrets.db_user }}"
      DB_PASS: "{{ itpol_valg_secrets.db_pass }}"