---
- name: ouroboros container
  docker_container:
    name: ouroboros
    image: pyouroboros/ouroboros
    restart_policy: unless-stopped
    networks:
      - name: external_services
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/root/.docker/config.json
    env:
      LABEL_ENABLE: "true"
      LABELS_ONLY: "true"
      CLEANUP: "true"
      LATEST: "true"
      CRON: "*/1 * * * *"
    command: ["-N", "slack://Ouroboros@{{ slack_tokens }}/#ung_infrastructure"]